id: P000019
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ཆོས་བཤད་གཞན་ཕན་ནོར་བུ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་གྲོལ།
  layers:
  - book_title
  - author
  - quotation
  id: SHE-SHAP-13
web_metadata:
  title:
    en: The Beneficial Jewel:The Public Teaching of Shabkar
    bo: ཆོས་བཤད་གཞན་ཕན་ནོར་བུ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 13
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༡༣
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-13
  category:
    en: Dharma Teaching
    bo: ཆོས་བསླབ་བྱ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-13.epub
  description:
    en: ''
    bo: ''
